How-The-Turntables/Grace-Shopper-2021

server/db/models/shopping/orderDetail.js, server/db/seed.js
Order_Details data layer completed
=> orderDetail data layer complete

package.json
Trying to fix Travis issue by adding exit flag to mocha
=> added exit flag to mocha

server/api/products.js, server/api/router.js, test/routes.spec.js
This is a new route that takes an id of the product and displays the details for it:
/api/products/:id
=> created a route for a single product

server/api/artists.js, test/routes.spec.js
This is just the route for the artists. Once it is approved I will go back and add it to the routes.js
=> created the artists route

package.json, server/db/index.js, server/db/models/products/album.js, server/db/models/products/artist.js
created artist model
imported artist and album into index.js
=> Data Layer: created artist model

package-lock.json, package.json, server/db/models/products/artist.js, server/db/models/users/userAddress.js
added userAddress
updated Artist
updated Package.json with new github links (capn-krunch -> how-the-turntables)
=> Models: user address

package-lock.json, package.json, server/index.js
Added route for root / to static index.html
Added error handling for routes
Added Dependency: morgan
Added use express.json
=> Routes: added static route to root, added morgan, added error handling

.travis.yml, package-lock.json, server/db/models/products/album.js, server/db/models/products/review.js, server/db/models/shopping/orderDetail.js, server/db/seed.js, server/index.js, test/products.spec.js, test/shopping.spec.js
Hey everyone, I fixed the issue with mocha and nodemon: in the server/index.js I added an if statement around app.listen(port...
This has somehow fixed the issue and almost everything is working fine, there are 3 issues however:
1) database does not update when restarting the test
2) Emily, I had to comment out your test spec :(
3) The test specs for albums are not done yet
=> Fixed mocha and nodemon, see the description before approving 

server/index.js
re-ordered / and /api routes on server/index.js
=> Server: swapped root and api route order in server/index.js

server/db/db.js, server/db/models/products/album.js, server/db/seed.js, server/index.js, test/products.spec.js, test/shopping.spec.js, test/users.spec.js
=> New bug fight

server/api/orders.js, server/db/models/products/album.js, server/db/models/shopping/orderDetail.js, server/db/models/users/user.js, test/shopping.spec.js
modified the order test spec
updated model and routes
=> Test Spec: fixed order test spec?

server/db/models/products/artist.js, test/routes.spec.js
=> added unige true

package-lock.json, server/api/router.js, server/api/users.js
added user route and changed router file.
=> User route

.eslintrc.json, .prettierrc.json, package-lock.json, package.json, test/routes.spec.js
added eslint and prettier dev dependencies
added lint script - test linting
added lint:fix script - fix linting errors that can be automatically fixed
=> Development Env: eslint, prettier

package.json, server/api/artists.js, server/api/router.js, server/api/users.js, server/db/models/products/album.js, server/db/models/products/artist.js, test/routes.spec.js
some of my code wasn't in the previous test fix commit
=> test specs : merging test spec fixes w master

client/components/App.js, client/components/Home.js, client/components/index.js, client/styles.js
=> Home page component

client/redux/store.js, package-lock.json, package.json
gives you extra tools in the chrome console, you'll need the extension
=> Front End: added react/redux dev tools to redux store

client/components/App.js, client/components/CartView.js, client/components/Checkout.js, client/components/Footer.js, client/components/index.js, package-lock.json
Added Components and imports/exports for CartView, Checkout, Footer
=> Components

client/components/App.js, client/components/SingleArtist.js, client/components/index.js, client/redux/artists/artistReducers.js, client/redux/artists/artistThunkCreator.js, client/redux/rootReducer.js
Please take a look at the rootReducer, is this how we want to add new reducers? Or should artists and singleArtist share the same one?
=> Single artist component

package-lock.json, server/api/albums.js, server/api/artists.js, test/routes.spec.js
added routes for editing, deleting, adding artists/albums. added tests to check the post routes of both albums and artists. Yeah, 4 more tests are passing.
=> Adding / editing / deleting albums and artists

.gitignore, package-lock.json, package.json, server/api/auth.js, server/api/router.js, server/db/models/users/user.js, server/index.js
added authentication methods to User
added authentication API routes
created authentication middleware
=> Security: JWT authentication

client/components/LoginForm.js, client/redux/user/thunkCreators.js, server/api/auth.js, server/api/users.js, server/db/models/users/user.js, server/db/seed.js
=> Authentication: fixed authentication, authenticated user returned

client/components/Home.js, client/redux/albums/reducers.js, server/db/models/users/user.js, server/db/seed.js
removed: Promise.all...I think this is your error. You're already awaiting those responses...i believe the promise all is redundant.
removed: console.log of the token
=> Seed Data: cleanup

server/api/users.js
created: POST route for user
updated: PUT route for user (.trim())
added: authentication for GET route (by token, needs token passed in header)
=> Routes: user POST, GET, PUT

client/components/App.js, client/components/LoginForm.js, client/components/LoginView.js, client/redux/rootReducer.js, client/redux/user/_thunkCreators(delete later).js, client/redux/user/actionCreators.js, client/redux/user/userActions.js, client/redux/user/userReducer.js, package-lock.json
The mother***** login and redirecting to home page.
=> User auth redux

client/components/App.js, client/components/CartView.js, client/redux/shopping/thunkShopping.js, server/api/orders.js, server/db/index.js, server/db/models/products/album.js, server/db/models/products/artist.js, server/db/models/products/review.js, server/db/models/shopping/orderDetail.js, server/db/models/shopping/orderItem.js, server/db/models/users/user.js, server/db/models/users/userAddress.js
=> Can pull the cart after the user logs in!!!!

client/components/AllAlbums.js, client/components/App.js, client/components/FilterSort.js, client/components/SingleAlbum.js, client/components/index.js, client/redux/albums/actionCreators.js, client/redux/albums/reducers.js, client/redux/albums/thunkCreators.js, client/redux/artists/artistReducers.js, client/redux/rootReducer.js, client/redux/types/index.js, server/api/albums.js
=> Filter sort take 2

client/components/Nav.js
small changes to navbar using material-ui
=> a little bit of a nicer navbar

client/components/AdminPage.js, client/components/AllUsers.js, client/components/App.js, client/components/Nav.js, client/components/index.js
Created AllUsers and AdminPage react components.
=> started AdminPage

client/components/AddReview.js, client/components/FilterSort.js, client/components/SingleAlbum.js, client/components/index.js, client/redux/albums/albumActions.js, client/redux/reviews/reviewActions.js, client/redux/reviews/reviewReducer.js, client/redux/rootReducer.js, server/api/albums.js, server/db/models/products/review.js
Review form opens with button click on single album view
issues to fix tomorrow:
- not mapping through reviews properly so they're not displaying on single album view
- new review is not saving state fields in db. Db is only saving initial state.
=> Added review form component into single album view

package.json, server/db/models/users/user.js, test/users.spec.js
added: afterCreate hook to User, creates a new cart instance for the user.
updated: package.json to include start script for Heroku
updated: package.json to exclude changes on entire front end folder from restarting server --ignore client/  (added the /)
=> Users: added user.afterCreate to create a cart instance

client/components/CartView.js
There was a small misspelling error in the cart componentDidMount
=> Cart bug fix

client/components/Nav.js, package-lock.json
Added account link for logged in users
=> Navigation: added account link for non-admin users

client/components/LoginForm.js, client/components/SignUpForm.js
Added: link to login form
Working: registration form
Needs: Style
Needs: thunk to call POST route for user creation, then login with token
=> Register: form working, needs thunk to call POST route
